version: '3.3'
service:
  mysql:
    image: mysql:8.1.0
    environment: 
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'ndmc'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    port:
      -"3307:3306"
    networks: 
      - connect
  adminer:
    image: adminer:4
    port:
      - "8081:8080"
    networks: 
      - connect
networks:
  connect:
  