 
version: '3.8'
services:
    postgres_db:
        image: postgres:13.5
        container_name: crud
        restart: always
        environment:
            - POSTGRES_USER=ndmc
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=ndmc_db
        volumes:
            - postgres_db:/var/lib/postgresql/data
        ports:
            - '5432:5432'
volumes:
    postgres_db:
        driver: local

  # deamon/background mode
  # docker compose -f ./dockercompose.yaml up -d
  # docker compose -f ./docker-compose.yaml down
  # docker compose up -d